version: '3.9'


services:
    static:
        container_name: static
        image: nginx
        volumes:
            - ./src:/usr/share/nginx/html

    proxy:
        container_name: proxy
        image: nginx
        ports:
            - 3002:80 
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        