version: '3.9'


services:

    web:
        container_name: web2
        build: 
            context: ../app
        volumes:
        - ../app:/usr/app/
        - /usr/app/node_modules
        ports:
        - "3000:3000"

    client:
        image: nginx
        ports:
            - 8001:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf