version: '3.9'


services:

    web:
        container_name: web2
        build: 
            context: ../app
        volumes:
        - ../app:/usr/app/
        - /usr/app/node_modules
        ports:
        - "8001:3000"

    client:
        image: nginx
        ports:
            - 8002:80
        volumes:
            - ../nginx-sample/src:/usr/share/nginx/html